//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHHC.Persistences
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyRank
    {
        public System.Guid RowID { get; set; }
        public Nullable<int> Year { get; set; }
        public string Insurer { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public Nullable<double> MarketShare { get; set; }
    }
}
