//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHHC.Persistences
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactForm
    {
        public System.Guid ID { get; set; }
        public string ContactReason { get; set; }
        public string FirsrtName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<BHHC.DTO.Enums.ContactTime> ContactTime { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
    }
}
